apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  containers:
  - env:
    - name: BUCKET_NAME
      value: XXXXXXXXX
    - name: IAM_USER_KEY
      value: XXXXXXXXX
    - name: IAM_USER_SECRET
      value: XXXXXXXXX
    - name: PORT
      value: "3000"
    - name: REDIS_IP
      value: redis
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      value: "XXXXXXXXX"
    image: [USERNAME]/[REPOSITORY_NAME]:[API_TAG]
    name: api
    ports:
    - containerPort: 3000
    resources: {}
  restartPolicy: OnFailure
status: {}
