apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: website
  name: website
spec:
  containers:
  - env:
    - name: API_IP
      value: api
    - name: API_PORT
      value: "3000"
    - name: PORT
      value: "8080"
    image: [USERNAME]/[REPOSITORY_NAME]:[WEBSITE_TAG]
    name: website
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
