# Default values for website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  username: USERNAME
  repository: REPOSITORY_NAME
  tag: WEBSITE_TAG
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

website:
  port: 8080
  env:
    API_IP: api
    API_PORT: "3000"
    PORT: "8080"

resources: {}
