apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.15.0 ()
  creationTimestamp: null
  labels:
    app: {{ template "website.name" . }}
    chart: {{ template "website.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    io.kompose.service: {{ template "website.name" . }}
  name: {{ template "website.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.port | quote }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "website.name" . }}
    release: {{ .Release.Name }}
    io.kompose.service: {{ template "website.name" . }}
status:
  loadBalancer: {}
