# Default values for loadbalancer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  username: dockercloud
  repository: haproxy
  tag: latest
  pullPolicy: IfNotPresent

storage:
  name: claim0
  mode: ReadWriteOnce
  capacity: "100Mi"

service:
  type: ClusterIP
  port: 80

loadbalancer:
  strategy: Recreate
  restartPolicy: Always
  port: 80
  env:
    BALANCE: leastconn

resources: {}
