# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  username: USERNAME
  repository: REPOSITORY_NAME
  tag: WEBSITE_TAG
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

api:
  port: 3000
  env:
    BUCKET_NAME: XXXXXXXXX
    IAM_USER_KEY: XXXXXXXXX
    IAM_USER_SECRET: XXXXXXXXX
    PORT: "3000"
    REDIS_IP: redis
    REDIS_PORT: "6379"
    REDIS_PASSWORD: XXXXXXXXX

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
