# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  username: xxxx
  repository: xxxx
  tag: xxxx
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

api:
  port: 3000
  env:
    BUCKET_NAME: uploadvalidate
    IAM_USER_KEY: xxxx
    IAM_USER_SECRET: xxxx
    PORT: "3000"
    REDIS_IP: redis-master
    REDIS_PORT: "6379"
    REDIS_PASSWORD: "xxxx"

resources: {}
