apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: "{{ template "loadbalancer.name" . }}-{{ .Values.storage.name }}"
  name: "{{ template "loadbalancer.name" . }}-{{ .Values.storage.name }}"
spec:
  accessModes: 
    - {{ .Values.storage.mode }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
status: {}